runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /img
  static_dir: img
- url: /mail
  static_dir: mail
- url: /vendor
  static_dir: vendor
  
  
- url: /.*
  script: main.app


libraries:
- name: jinja2
  version: latest
 